#!/usr/bin/python
import os
import re
import traceback
import threading
import time
import json
import sys
import pytz
import requests
from calendar import timegm
from datetime import datetime, timedelta
from select import select
from evdev import ecodes, InputDevice, list_devices
from evdev.events import KeyEvent
from hosted import config, node, device
from ibquery import InfoBeamerQuery

config.restart_on_update()

if config.timezone == 'device':
    schedule_tz = config.metadata_timezone
else:
    schedule_tz = pytz.timezone(config.timezone)

def iter_tiles(types=None):
    for schedule in config.schedules:
        for page in schedule['pages']:
            for tile in page['tiles']:
                if not types or tile['type'] in types:
                    yield tile
    for layout in config.layouts:
        for tile in layout['tiles']:
            if not types or tile['type'] in types:
                yield tile

all_timezones = {
    schedule_tz.zone: schedule_tz,
}
for tile in iter_tiles('time'):
    tile_tz = tile['config'].get('timezone')
    if tile_tz:
        all_timezones[tile_tz] = pytz.timezone(tile_tz)
print >>sys.stderr, all_timezones

countdowns = set()
for tile in iter_tiles('countdown'):
    countdowns.add(tile['config'].get('target', ''))
print >>sys.stderr, countdowns


try:
    sim_date, sim_time = config.time.strip().split()
    d, m, y = sim_date.split('.')
    ho, mi = sim_time.split(':')

    utc_now = datetime.now(pytz.utc)
    local_now = utc_now.astimezone(schedule_tz)
    simulated = schedule_tz.localize(datetime(int(y), int(m), int(d), int(ho), int(mi), 00))

    diff =  simulated - local_now
except:
    diff = timedelta()

print >>sys.stderr, "timedelta for simulation: %r" % (diff,)

devices = {}
def update_devices():
    new = set(list_devices("/dev/input/"))
    old = set(devices.keys())

    for device_name in new - old:
        devices[device_name] = InputDevice(device_name)

    for device_name in old - new:
        del devices[device_name]

def send_clock(tz):
    utc_now = datetime.now(pytz.utc) + diff

    unix = timegm(utc_now.timetuple()) + utc_now.microsecond / 1000000.
    local_now = utc_now.astimezone(tz)
    # print >>sys.stderr, 'local now', local_now

    since_midnight = (
        local_now -
        local_now.replace(hour=0, minute=0, second=0, microsecond=0)
    )
    since_midnight = since_midnight.seconds + since_midnight.microseconds / 1000000.

    monday = (local_now - timedelta(days = local_now.weekday())).replace(hour=0, minute=0, second=0, microsecond=0)
    since_monday = local_now - monday
    since_monday = since_monday.days * 86400 + since_monday.seconds + since_monday.microseconds / 1000000.

    node['/clock/%s' % tz.zone](json.dumps(dict(
        year = local_now.year,
        month = local_now.month,
        day = local_now.day,
        unix = unix,
        dow = local_now.weekday(),
        since_midnight = since_midnight,
        since_monday = int(since_monday),
        week_hour = int(since_monday / 3600),
        diff = diff.total_seconds(),
    )))

def send_countdown(countdown_target):
    try:
        target = datetime.strptime(countdown_target, "%Y-%m-%d %H:%M:%S")
    except ValueError as err:
        traceback.print_exc()
        return
    target = schedule_tz.localize(target)
    target = target.astimezone(pytz.UTC)
    unix = timegm(target.timetuple())
    node['/countdown'](json.dumps(dict(
        target = countdown_target,
        unix = unix,
    )))

def device_event(event):
    print >>sys.stderr, event

    if event.code in ecodes.BTN:
        btn = ecodes.BTN[event.code]
        if not isinstance(btn, list):
            btn = [btn]
        for name in btn:
            node.send('/event/pad:%s' % json.dumps(dict(
                key = name.replace("BTN_", "pad_").lower(),
                action = {
                    KeyEvent.key_up: "up",
                    KeyEvent.key_down: "down",
                }[event.value],
            )))
    
    if event.type == ecodes.EV_KEY and event.code in ecodes.KEY:
        node.send('/event/keyboard:%s' % json.dumps(dict(
            key = ecodes.KEY[event.code].replace("KEY_", "").lower(),
            action = {
                KeyEvent.key_up: "up",
                KeyEvent.key_down: "down",
                KeyEvent.key_hold: "hold",
            }[event.value],
        )))

def monitor_input():
    update_devices()
    r, w, e = select(devices.values(), [], [], 1)
    for event in r:
        try:
            for ev in event.read():
                device_event(ev)
        except IOError:
            # device disconnected
            pass

def send_time():
    if time.time() < 10000000:
        print >>sys.stderr, "too soon"
        time.sleep(1)
        return
    for name, tz in all_timezones.iteritems():
        send_clock(tz)
    for target in countdowns:
        send_countdown(target)
    time.sleep(0.5)

def monitor_gpio():
    pins = set()
    for schedule in config.schedules:
        for page in schedule['pages']:
            key = page.get('interaction', {}).get('key', '')
            m = re.match('gpio_(.*)', key)
            if m:
                pins.add(int(m.group(1)))
    if not pins:
        time.sleep(120)
        return

    print >>sys.stderr, "gpios active: %s" % (pins,)
    for pin in pins:
        device.gpio.monitor(pin)
    for pin, high in device.gpio.poll_forever():
        if high:
            node.send('/event/gpio:%s' % json.dumps(dict(
                pin = pin,
            )))

def screen_toggle():
    ib = InfoBeamerQuery("127.0.0.1")
    con = ib.node('root/__fallback__').io(raw=True)
    for line in con:
        line = line.strip()
        print >>sys.stderr, "screen power: %s" % (not config.poweroff or line == "1",)
        # device.screen(
        #     on = not config.poweroff or line == "1"
        # )

def fetch_device_info():
    """Fetch device information from info-beamer API for the current device"""
    try:
        # Get the device's own API endpoint from metadata
        # The metadata 'api' field contains the base API URL for this device
        device_api_base = config.metadata.get('api')
        
        if not device_api_base:
            print >>sys.stderr, "No device API endpoint found in metadata"
            return
        
        # The metadata also contains device-specific info we can use directly
        device_serial = device.serial
        
        # Try to get device ID from metadata first
        # Check various possible metadata keys for device ID
        device_id = None
        metadata_keys_to_check = ['device_id', 'id', 'setup_id', 'device']
        for key in metadata_keys_to_check:
            if key in config.metadata:
                value = config.metadata[key]
                # If it's a dict, try to get 'id' from it
                if isinstance(value, dict) and 'id' in value:
                    device_id = value['id']
                    break
                # Otherwise use the value directly if it looks like an ID
                elif value:
                    # Check if it's a number or numeric string
                    try:
                        if isinstance(value, (int, long)):
                            device_id = value
                            break
                        elif isinstance(value, str) and value.isdigit():
                            device_id = int(value)
                            break
                    except:
                        pass
        
        print >>sys.stderr, "Device ID from metadata: %s" % device_id
        
        # Construct device info from available metadata and API
        # First, try to get full device data from the API using OnDeviceAPIs
        device_data = None
        
        try:
            # Use OnDeviceAPIs which handles authentication automatically
            from hosted import OnDeviceAPIs
            api = OnDeviceAPIs(config)
            # Try to get device info - the API endpoint might be 'device' or we need to construct the URL
            try:
                # Try using the device API endpoint if available
                if 'device' in api.list():
                    device_api = api.device
                    device_data = device_api.get()
                else:
                    # Try constructing the device endpoint URL directly
                    # The device endpoint is typically at /api/v1/device/{device_id}
                    # But we can try /device which should return current device info
                    response = api.session.get(device_api_base + '/device', timeout=10)
                    response.raise_for_status()
                    api_response = response.json()
                    if api_response.get('ok'):
                        device_data = api_response.get('device', {})
            except Exception as e:
                print >>sys.stderr, "Could not fetch from device API using OnDeviceAPIs: %s" % str(e)
                device_data = None
        except Exception as e:
            print >>sys.stderr, "Could not initialize OnDeviceAPIs: %s" % str(e)
            device_data = None
        
        # If we still don't have device data but we have a device_id, try using call_device_api
        if not device_data and device_id:
            print >>sys.stderr, "Trying call_device_api with device_id: %s" % device_id
            print("---------------------------------call_device_api-------------------------------------------------------------------------------")
            api_response = call_device_api(device_id)
            if api_response:
                # The response might be wrapped in {'ok': True, 'device': {...}} or just be the device data
                if isinstance(api_response, dict):
                    if 'ok' in api_response and 'device' in api_response:
                        device_data = api_response['device']
                    elif 'id' in api_response:  # Might be device data directly
                        device_data = api_response
        
        # Always test the API call if we have a device_id (for logging/debugging)
        if device_id:
            print >>sys.stderr, "[TEST] ========================================"
            print >>sys.stderr, "[TEST] Testing API call to device %s" % device_id
            print >>sys.stderr, "[TEST] ========================================"
            test_response = call_device_api(device_id)
            if test_response:
                print >>sys.stderr, "[TEST] API call successful!"
                print >>sys.stderr, "[TEST] Response type: %s" % type(test_response).__name__
                if isinstance(test_response, dict):
                    print >>sys.stderr, "[TEST] Response keys: %s" % str(test_response.keys())
                    # If response is wrapped in {'ok': True, 'device': {...}}, show the device data
                    if 'ok' in test_response and 'device' in test_response:
                        print >>sys.stderr, "[TEST] Unwrapped device data: %s" % json.dumps(test_response['device'], indent=2, default=str)
                    else:
                        print >>sys.stderr, "[TEST] Full response: %s" % json.dumps(test_response, indent=2, default=str)
                else:
                    print >>sys.stderr, "[TEST] Response: %s" % str(test_response)
            else:
                print >>sys.stderr, "[TEST] API call failed or returned None"
            print >>sys.stderr, "[TEST] ========================================"
        
        # Send the COMPLETE API response (all fields) for display
        if device_data:
            # Use the full device data from API as-is
            device_info = device_data
            # Just add serial number from system if not already present
            if 'serial' not in device_info:
                device_info['serial'] = device_serial
            # Ensure device ID is set
            if 'id' not in device_info or not device_info['id']:
                if device_id:
                    device_info['id'] = device_id
            print >>sys.stderr, "Device info fetched from API - Fields: %d" % len(device_info.keys())
        else:
            # Fallback: use metadata only
            device_info = {
                'id': device_id if device_id else 'N/A',
                'serial': device_serial,
                'description': 'Device %s' % device_serial,
                'location': 'N/A',
                'run': 'N/A',
                'is_online': True,
                'last_contact': int(time.time()),
                'uptime': 0,
                'timezone': config.metadata.get('timezone', 'UTC'),
            }
            print >>sys.stderr, "Device info using fallback data (device_id: %s)" % device_id
        
        print >>sys.stderr, "Sending device info to Lua - Size: %d bytes, Device ID: %s" % (
            len(json.dumps(device_info)), device_info.get('id', 'N/A')
        )
        
        # Send to Lua node
        node.send('/device_info:%s' % json.dumps(device_info))
        
    except AttributeError as e:
        print >>sys.stderr, "Error accessing device metadata: %s" % str(e)
        print >>sys.stderr, "This might be running outside of info-beamer hosted environment"
    except Exception as e:
        print >>sys.stderr, "Unexpected error in fetch_device_info: %s" % str(e)
        traceback.print_exc()

def call_device_api(device_id, endpoint_path=""):
    """
    Call the info-beamer device API endpoint.
    
    Args:
        device_id: The device ID (e.g., 43493)
        endpoint_path: Optional path to append after /device/{device_id}/ (e.g., "status", "config")
    
    Returns:
        dict: The API response, or None on error
    """
    try:
        # Log metadata API URL for debugging
        device_api_base = config.metadata.get('api')
        print >>sys.stderr, "[API] Metadata API URL: %s" % device_api_base
        
        # Construct the endpoint path
        # Default to 'sensor' endpoint if no endpoint_path specified
        if endpoint_path:
            full_endpoint = "/device/%d/%s" % (device_id, endpoint_path.rstrip('/'))
        else:
            full_endpoint = "/device/%d/sensor" % device_id
        
        print >>sys.stderr, "[API] Calling device API endpoint: %s" % full_endpoint
        
        # Try to get on_device_token from metadata or extract from API URL
        on_device_token = config.metadata.get('on_device_token')
        if not on_device_token and device_api_base:
            # Try to extract on_device_token from the API URL
            # Format: https://info-beamer.com/api/v1/device/43493/on-device/{token}
            import re
            match = re.search(r'/on-device/([^/]+)', device_api_base)
            if match:
                on_device_token = match.group(1)
                print >>sys.stderr, "[API] Extracted on_device_token from API URL"
        
        # Try using HostedAPI first (more reliable authentication and URL handling)
        try:
            if on_device_token:
                from hosted import OnDeviceAPIs, HostedAPI
                api = OnDeviceAPIs(config)
                hosted_api = HostedAPI(api, on_device_token)
                print >>sys.stderr, "[API] Using HostedAPI with on_device_token"
                response = hosted_api.get(full_endpoint)
                print >>sys.stderr, "[API] Raw response type: %s" % type(response).__name__
                print >>sys.stderr, "[API] Raw response: %s" % json.dumps(response, indent=2, default=str)
                
                # Check if response is wrapped in {'ok': True, 'device': {...}}
                if isinstance(response, dict):
                    if 'ok' in response and 'device' in response:
                        device_data = response['device']
                        print >>sys.stderr, "[API] Unwrapped device data: %s" % json.dumps(device_data, indent=2, default=str)
                        return device_data
                    elif 'id' in response:  # Already the device object
                        print >>sys.stderr, "[API] Response is device object directly"
                        return response
                
                return response
            else:
                print >>sys.stderr, "[API] No on_device_token found in metadata or API URL"
        except Exception as e:
            print >>sys.stderr, "[API] Could not use HostedAPI: %s" % str(e)
            traceback.print_exc()
        
        # Fallback: Use OnDeviceAPIs to get API index and construct URL properly
        try:
            from hosted import OnDeviceAPIs
            api = OnDeviceAPIs(config)
            
            # Get the API index to find the correct base URL
            # The API index response contains URLs for different endpoints
            api_index = api.get_api_index()
            print >>sys.stderr, "[API] Using OnDeviceAPIs session (fallback)"
            print >>sys.stderr, "[API] Available API endpoints: %s" % str(api.list() if hasattr(api, 'list') else 'N/A')
            
            # Try to get base URL from a known endpoint in the index
            # The 'device' endpoint should give us the pattern
            base_api_url = None
            if 'device' in api_index:
                device_endpoint_url = api_index['device']['url']
                # Extract base URL by removing the endpoint-specific part
                # e.g., if URL is https://info-beamer.com/api/v1/device/123, base is https://info-beamer.com/api/v1
                import re
                match = re.match(r'(https?://[^/]+/api/v1)', device_endpoint_url)
                if match:
                    base_api_url = match.group(1)
                else:
                    # Try to extract by removing /device/... part
                    if '/device/' in device_endpoint_url:
                        base_api_url = device_endpoint_url.split('/device/')[0]
            
            # If we couldn't extract from index, try from metadata
            if not base_api_url:
                device_api_base = config.metadata.get('api')
                if device_api_base:
                    # Extract base URL (remove on-device and device-specific paths)
                    import re
                    match = re.search(r'(https?://[^/]+/api/v1)', device_api_base)
                    if match:
                        base_api_url = match.group(1)
                    elif '/on-device' in device_api_base:
                        base_api_url = device_api_base.split('/on-device')[0]
            
            if not base_api_url:
                print >>sys.stderr, "[API] Could not determine base API URL"
                return None
            
            # Construct full URL
            full_url = base_api_url.rstrip('/') + full_endpoint
            print >>sys.stderr, "[API] Base API URL: %s" % base_api_url
            print >>sys.stderr, "[API] Full URL: %s" % full_url
            
            response = api.session.get(full_url, timeout=10)
            print >>sys.stderr, "[API] HTTP Status: %d" % response.status_code
            response.raise_for_status()
            response_data = response.json()
            print >>sys.stderr, "[API] Raw response type: %s" % type(response_data).__name__
            print >>sys.stderr, "[API] Raw response: %s" % json.dumps(response_data, indent=2, default=str)
            print("---------------------------------Response Data-------------------------------------------------------------------------------")
            # Check if response is wrapped in {'ok': True, 'device': {...}}
            if isinstance(response_data, dict):
                if 'ok' in response_data and 'device' in response_data:
                    device_data = response_data['device']
                    print >>sys.stderr, "[API] Unwrapped device data: %s" % json.dumps(device_data, indent=2, default=str)
                    return device_data
                elif 'id' in response_data:  # Already the device object
                    print >>sys.stderr, "[API] Response is device object directly"
                    return response_data
            
            return response_data
        except Exception as e:
            print >>sys.stderr, "[API] Could not call device API: %s" % str(e)
            traceback.print_exc()
            return None
            
    except Exception as e:
        print >>sys.stderr, "Error in call_device_api: %s" % str(e)
        traceback.print_exc()
        return None

def monitor_device_api():
    """Periodically fetch device information"""
    while True:
        fetch_device_info()
        time.sleep(60)  # Fetch every 60 seconds

def run_in_thread(fn):
    def wrap():
        try:
            while 1:
                fn()
        except Exception:
            traceback.print_exc()
            os._exit(1)
    thread = threading.Thread(target=wrap)
    thread.daemon = True
    thread.start()

if __name__ == "__main__":
    run_in_thread(send_time)
    run_in_thread(screen_toggle)
    run_in_thread(monitor_input)
    run_in_thread(monitor_gpio)
    run_in_thread(monitor_device_api)

    while 1: time.sleep(1000)
